import Head from "next/head";

import Link from "next/link";
import styles from "@/styles/Home.module.css";
import { useState } from "react";

export default function Home({ list }) {
  const [search, setSearch] = useState("");
  const [gameSearch, setGameSearch] = useState([]);
 
  

  const handleSearch = async () => {
    if (search !== "") {
      const result = await fetch(
        `http://localhost:3000/api/pesquisa/${search}`
      );
      const json = await result.json();
      setGameSearch(json.list);
      console.log(gameSearch);
    }
  };
  return (
    <>
      <Head>
        <title>GAMEBOXD</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.topbar}>
          <div style={{ display: "flex", alignItems: "center" }}>
            <h1>GAME</h1>
            <span>BOXD</span>
          </div>
          <input
            type="text"
            onFocus={() => {
              
              
            }}
            value={search}
            onChange={(event) => {
              setSearch(event.target.value);
              handleSearch();
            }}
          />
          {search && (
            <div className={styles.resultados}>
              {gameSearch.map((item) => {
                <Link href={`/jogo/${item.id}`}>
                  <div className={styles.jogoPesquisa}>
                    <img src={item.background_image} />
                    <div>
                      <span>{item.name}</span>
                    </div>
                  </div>
                </Link>
              })}
            </div>
          )}
        </div>
        <div className={styles.jogos}>
          {list.map((item) => (
            <Link href={`/jogo/${item.id}`}>
              <div className={styles.jogo}>
                <img src={item.background_image} />
                <div className={styles.gameinfo}>
                  <span>{item.name}</span>
                </div>
              </div>
            </Link>
          ))}
        </div>
      </main>
    </>
  );
}

export async function getServerSideProps() {
  const res = await fetch("http://localhost:3000/api/jogos");
  const json = await res.json();

  return {
    props: {
      list: json.list,
    },
  };
}
